import { Clue, Scene, Puzzle } from './mystery';

export const CLUES: Clue[] = [
  {
    id: 'A1',
    name: '撕碎的信纸',
    type: 'document',
    scene: 'study',
    description: '一封被撕碎的信，部分内容仍可辨认',
    detail: '信纸碎片上写着："...必须阻止他...遗产分配不公...我会..." 字迹显示是死者亲笔，但被匆忙撕毁。',
    visibleTo: 'A',
    icon: '📄',
  },
  {
    id: 'A2',
    name: '安眠药瓶',
    type: 'evidence',
    scene: 'study',
    description: '床头柜上的安眠药瓶',
    detail: '药瓶标签显示是"安定"，处方日期为三天前。瓶内药片数量与处方不符，似乎被使用过。',
    visibleTo: 'A',
    icon: '💊',
  },
  {
    id: 'A3',
    name: '保险箱钥匙',
    type: 'evidence',
    scene: 'bedroom',
    description: '在枕头下发现的小钥匙',
    detail: '一把精致的铜钥匙，钥匙柄上刻着"书房保险箱"字样。这可能是打开书房保险箱的关键。',
    visibleTo: 'A',
    icon: '🔑',
  },
  {
    id: 'A4',
    name: '陈志远日记',
    type: 'document',
    scene: 'bedroom',
    description: '死者生前记录的私人日记',
    detail: '日记记录了最近一个月的事情："弟弟又来要钱了，父亲留下的遗产他一分都没得到。我必须坚持父亲的决定。"',
    visibleTo: 'A',
    icon: '📔',
  },
  {
    id: 'A5',
    name: '厨师证词',
    type: 'testimony',
    scene: 'kitchen',
    description: '厨师李阿姨的口述记录',
    detail: '"那天晚上大概十点左右，我听到书房里有争吵声。好像有两个人的声音，但听不清说什么。后来就安静了。"',
    visibleTo: 'A',
    icon: '🗣️',
  },
  {
    id: 'A6',
    name: '茶杯残留物',
    type: 'evidence',
    scene: 'kitchen',
    description: '书房茶杯中的残留液体',
    detail: '茶杯中残留的液体经初步检测，含有微量不明化学物质。这可能是导致死亡的关键证据。',
    visibleTo: 'A',
    icon: '🫖',
  },
  {
    id: 'A7',
    name: '烧毁的文件',
    type: 'document',
    scene: 'study',
    description: '壁炉中烧毁的文件残骸',
    detail: '文件已被烧得面目全非，但从残留的纸张边缘可以辨认出这是一份合同或协议类文件。',
    visibleTo: 'A',
    icon: '🔥',
  },
  {
    id: 'B1',
    name: '泥泞脚印',
    type: 'environment',
    scene: 'garden',
    description: '花园小径上的新鲜脚印',
    detail: '脚印从花园延伸到地下室入口，泥土显示这是雨后留下的痕迹。鞋码约42码，是男鞋。',
    visibleTo: 'B',
    icon: '👣',
  },
  {
    id: 'B2',
    name: '地下室钥匙',
    type: 'evidence',
    scene: 'garden',
    description: '藏在花盆下的钥匙',
    detail: '一把生锈的铁钥匙，藏在花园角落的花盆下面。这把钥匙能打开地下室的门。',
    visibleTo: 'B',
    icon: '🗝️',
  },
  {
    id: 'B3',
    name: '弟弟的日记',
    type: 'document',
    scene: 'basement',
    description: '在地下室发现的笔记本',
    detail: '陈志明的私人日记："哥哥太自私了，父亲留下的遗产他独吞。我不会让他得逞的。我已经有了计划..."',
    visibleTo: 'B',
    icon: '📓',
  },
  {
    id: 'B4',
    name: '遗嘱副本',
    type: 'document',
    scene: 'basement',
    description: '藏在暗格里的文件',
    detail: '一份遗嘱的复印件，显示原遗嘱将财产的70%留给陈志远，30%留给陈志明。但有人试图修改这个比例。',
    visibleTo: 'B',
    icon: '📜',
  },
  {
    id: 'B5',
    name: '园丁证词',
    type: 'testimony',
    scene: 'garden',
    description: '园丁老王的口述',
    detail: '"那天晚上下雨，我看到有人从后门溜出去，又从地下室方向回来。那个人穿着深色外套，看不清脸。"',
    visibleTo: 'B',
    icon: '💬',
  },
  {
    id: 'B6',
    name: '毒药收据',
    type: 'document',
    scene: 'basement',
    description: '一张购物收据',
    detail: '收据显示一周前在某化工店购买了"氰化钾"，购买者签名为"陈志明"。这是决定性的证据！',
    visibleTo: 'B',
    icon: '🧾',
  },
  {
    id: 'B7',
    name: '神秘照片',
    type: 'evidence',
    scene: 'basement',
    description: '一张被撕掉一半的照片',
    detail: '照片中陈志明与一位神秘女子站在一起，背景是某个餐厅。女子身份不明，但两人关系亲密。',
    visibleTo: 'B',
    icon: '🖼️',
  },
  {
    id: 'C1',
    name: '死亡时间报告',
    type: 'document',
    scene: 'study',
    description: '法医初步报告',
    detail: '死亡时间推断：当晚22:00-23:00之间。死因初步判定为中毒，具体毒物待进一步检测。',
    visibleTo: 'both',
    icon: '📋',
  },
  {
    id: 'C2',
    name: '通话记录',
    type: 'document',
    scene: 'study',
    description: '死者手机通话记录',
    detail: '最后一通电话打给"弟弟"，通话时间21:30，持续约5分钟。之后手机被关机。',
    visibleTo: 'both',
    icon: '📱',
  },
];

export const SCENES: Scene[] = [
  {
    id: 'study',
    name: '书房',
    description: '案发现场，陈志远被发现死亡的地方。书架上摆满了法律书籍，桌上还有未处理完的文件。',
    image: 'study',
    visibleTo: 'both',
    clues: ['A1', 'A2', 'A7', 'C1', 'C2'],
    connections: ['bedroom', 'kitchen'],
  },
  {
    id: 'bedroom',
    name: '主卧室',
    description: '陈志远的私人卧室。床铺整洁，但枕头下似乎藏着什么。',
    image: 'bedroom',
    visibleTo: 'A',
    clues: ['A3', 'A4'],
    connections: ['study'],
  },
  {
    id: 'kitchen',
    name: '厨房',
    description: '宽敞的厨房，厨师李阿姨正在接受询问。角落里的茶具引起了你的注意。',
    image: 'kitchen',
    visibleTo: 'A',
    clues: ['A5', 'A6'],
    connections: ['study'],
  },
  {
    id: 'garden',
    name: '花园',
    description: '雨后的花园泥泞不堪。园丁老王正在修剪灌木，地面上有奇怪的痕迹。',
    image: 'garden',
    visibleTo: 'B',
    clues: ['B1', 'B2', 'B5'],
    connections: ['basement'],
  },
  {
    id: 'basement',
    name: '地下室',
    description: '阴暗潮湿的地下室，堆满了旧家具和杂物。角落里有一个上锁的柜子。',
    image: 'basement',
    visibleTo: 'B',
    clues: ['B3', 'B4', 'B6', 'B7'],
    connections: ['garden'],
  },
];

export const PUZZLES: Puzzle[] = [
  {
    id: 'puzzle1',
    name: '打开保险箱',
    description: '书房的保险箱被锁住了，需要找到钥匙才能打开。',
    difficulty: 1,
    requiredClues: ['A3'],
    solution: 'use_key',
    reward: '获得完整遗书，显示陈志远曾打算修改遗嘱',
    solved: false,
  },
  {
    id: 'puzzle2',
    name: '拼凑信件',
    description: '撕碎的信纸和遗嘱副本似乎有某种关联...',
    difficulty: 2,
    requiredClues: ['A1', 'B4'],
    solution: 'combine_documents',
    reward: '发现遗产被篡改的证据，确认动机',
    solved: false,
  },
  {
    id: 'puzzle3',
    name: '确定凶手',
    description: '收集足够的证据后，可以尝试推断凶手身份。',
    difficulty: 3,
    requiredClues: ['A4', 'A6', 'B3', 'B6'],
    solution: 'chen_zhiming',
    reward: '锁定嫌疑人：陈志明',
    solved: false,
  },
  {
    id: 'puzzle4',
    name: '还原真相',
    description: '填写完整的案件报告，揭示真相。',
    difficulty: 4,
    requiredClues: ['A4', 'A5', 'A6', 'B3', 'B6', 'B1'],
    solution: 'full_report',
    reward: '游戏胜利！',
    solved: false,
  },
];

export const PLAYER_INFO = {
  A: {
    name: '林晓月',
    title: '侦探',
    description: '专业严谨的女侦探，擅长分析物证和文件。',
    theme: 'blue',
    avatar: '👩‍💼',
  },
  B: {
    name: '周明轩',
    title: '侦探',
    description: '敏锐直觉的男侦探，擅长发现隐藏痕迹和证人询问。',
    theme: 'green',
    avatar: '👨‍💼',
  },
};

export const CORRECT_ANSWER = {
  murderer: '陈志明',
  motive: '遗产争夺',
  method: '下毒谋杀',
  time: '22:00-23:00',
  evidence: '毒药收据、茶杯残留物、弟弟日记、脚印',
};
